spring:
  logging:
    file: logs/application-debug.log
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      root: WARN
      org.springframework.web: DEBUG
      org.hibernate: INFO

  datasource:
    url: jdbc:postgresql://localhost:5432/CspMasterData
    username: postgres
    password: 273200
    driverClassName: org.postgresql.Driver
    time-zone: GMT+10

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      dialect:  org.hibernate.dialect.PostgreSQL13Dialect
      new_generator_mappings: false
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      cache:
        use_second_level_cache: false
        use_query_cache: false


