spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CspMasterData
    username: postgres
    password: 273200
    driverClassName: org.postgresql.Driver
    time-zone: GMT+10


  jpa:
    open-in-view: false
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      dialect:  org.hibernate.dialect.PostgreSQL95Dialect
      new_generator_mappings: false
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      cache:
        use_second_level_cache: false
        use_query_cache: false


